#!/usr/bin/env bash

ECHO=$(which echo)
NSUPDATE=$(which nsupdate)

# Get your public IP address in the quickest and fanciest
# way to if you have bind-tools installed
IP=`dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}'`

# Another way to get your public address. Only curl needed. It's a bit
# slower and it relies on 3rd party services which can or cannot be online.
#IP=`curl ifconfig.co`

# Set the DNS entry you want to update, please notice the final dot.
HOST="myhost.mydomain.com."

# Set the key provided by your DNS administrator
KEY="/etc/named/Kmydomain.com.+157+19553.key"

# Set the DNS server name or IP
SERVER="dnsserver.mydomain.net"

# Set the zone to modify, it can be any zone previous key has permissions to modify
ZONE="mydomain.com."

$ECHO "server $SERVER" > /tmp/nsupdate
$ECHO "debug yes" >> /tmp/nsupdate
$ECHO "zone $ZONE" >> /tmp/nsupdate
$ECHO "update delete $HOST" >> /tmp/nsupdate
$ECHO "update add $HOST 600 A $IP" >> /tmp/nsupdate
$ECHO "send" >> /tmp/nsupdate

$NSUPDATE -k ${KEY} -v /tmp/nsupdate 2>&1
